name: littledownloader_production

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api
    env_file:
      - .env.prod
    environment:
      RAILS_ENV: production
      DOWNLOADS_DIR: /downloads
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    ports: ["3008:80"]
    volumes:
      - type: bind
        source: ${DOWNLOADS_HOST_DIR}
        target: /downloads
    restart: unless-stopped

  jobs:
    build:
      context: .
      dockerfile: Dockerfile
      target: jobs
    env_file:
      - .env.prod
    environment:
      RAILS_ENV: production
      DOWNLOADS_DIR: /downloads
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    restart: unless-stopped
